In [45]:
import numpy as np

In [61]:
#python list to numpy array
list = ((1,2),(4,5),(7,8),(9,10))
arr_1 = np.array(list)
print(arr_1)

[[ 1  2]
 [ 4  5]
 [ 7  8]
 [ 9 10]]


In [11]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [15]:
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [29]:
np.random.rand(2,3)

array([[0.35440631, 0.69641574, 0.08469348],
       [0.34342122, 0.95102347, 0.92211642]])

In [55]:
arr_1.ndim

2

In [41]:
arr_1[0,1]

2

In [63]:
arr_1.reshape(2,4)

array([[ 1,  2,  4,  5],
       [ 7,  8,  9, 10]])

In [65]:
arr_1.flatten()

array([ 1,  2,  4,  5,  7,  8,  9, 10])

In [67]:
arr_1

array([[ 1,  2],
       [ 4,  5],
       [ 7,  8],
       [ 9, 10]])

In [69]:
arr_1.T

array([[ 1,  4,  7,  9],
       [ 2,  5,  8, 10]])

In [115]:
arr_2 = np.array((('a','b'),('c','d'),('e','f'),('h','i')))

In [113]:
arr_2

array([['a', 'b'],
       ['c', 'd'],
       ['e', 'f']], dtype='<U1')

In [117]:
np.concatenate([arr_1,arr_2],axis=0)

array([['1', '2'],
       ['4', '5'],
       ['7', '8'],
       ['9', '10'],
       ['a', 'b'],
       ['c', 'd'],
       ['e', 'f'],
       ['h', 'i']], dtype='<U21')

In [119]:
np.concatenate([arr_1, arr_2], axis=1)

array([['1', '2', 'a', 'b'],
       ['4', '5', 'c', 'd'],
       ['7', '8', 'e', 'f'],
       ['9', '10', 'h', 'i']], dtype='<U21')

In [127]:
np.hstack((arr_1,arr_2))

array([['1', '2', 'a', 'b'],
       ['4', '5', 'c', 'd'],
       ['7', '8', 'e', 'f'],
       ['9', '10', 'h', 'i']], dtype='<U21')

In [129]:
np.vstack((arr_1,arr_2))

array([['1', '2'],
       ['4', '5'],
       ['7', '8'],
       ['9', '10'],
       ['a', 'b'],
       ['c', 'd'],
       ['e', 'f'],
       ['h', 'i']], dtype='<U21')

In [131]:
np.stack((arr_1,arr_2))

array([[['1', '2'],
        ['4', '5'],
        ['7', '8'],
        ['9', '10']],

       [['a', 'b'],
        ['c', 'd'],
        ['e', 'f'],
        ['h', 'i']]], dtype='<U21')

In [133]:
np.split(arr_1,2)

[array([[1, 2],
        [4, 5]]),
 array([[ 7,  8],
        [ 9, 10]])]

In [143]:
arr = np.array(((12,1),(22,10)))
arr + 6
arr

array([[12,  1],
       [22, 10]])

In [147]:
arr + np.array([0, 2])

array([[12,  3],
       [22, 12]])